# ControlPlayer Configuration

discord:
  # Discord bot token (REQUIRED)
  token: "YOUR_TOKEN_HERE"

  # Prefix for Discord commands (customizable)
  prefix: "!"

  # Discord channels where commands are allowed (channel IDs)
  allowed-channels:
    - "123456789012345678"  # Replace with your channel ID
    - "987654321098765432"  # You can add more channels

  # Discord users allowed to use basic commands (user IDs)
  allowed-users:
    - "123456789012345678"  # Replace with your Discord ID
    - "987654321098765432"  # You can add more admin users

  # Discord users allowed to use the histstaff command (user IDs)
  # WARNING: This command reveals sensitive information!
  history-allowed-users:
    - "123456789012345678"  # Only high-level admins
    # - "another_admin_id"  # Uncomment and replace to add more

# Database Configuration
database:
  # Enable/disable logging system in the database
  enabled: true

  # Maximum number of records shown in the histstaff command
  max-history-records: 50

# Commands to execute on the Minecraft server
# Available placeholders: %player%, %duration%, %reason%
commands:
  # Command to ban (customizable for LiteBans, EssentialsX, etc.)
  ban: "ban %player% %duration% %reason%"

  # Command to kick
  kick: "kick %player% %reason%"

  # Command to mute
  mute: "mute %player% %duration% %reason%"

  # Command to unban
  unban: "unban %player%"

  # Command to unmute
  unmute: "unmute %player%"

# Example configurations for popular plugins:
#
# For LiteBans:
# ban: "litebans:ban %player% %duration% %reason%"
# mute: "litebans:mute %player% %duration% %reason%"
# kick: "litebans:kick %player% %reason%"
# unban: "litebans:unban %player%"
# unmute: "litebans:unmute %player%"
#
# For EssentialsX:
# ban: "essentials:ban %player% %reason%"
# mute: "essentials:mute %player% %duration% %reason%"
# kick: "essentials:kick %player% %reason%"
# unban: "essentials:unban %player%"
# unmute: "essentials:mute %player% remove"
#
# For AdvancedBan:
# ban: "advancedban:ban %player% %duration% %reason%"
# mute: "advancedban:mute %player% %duration% %reason%"
# kick: "advancedban:kick %player% %reason%"
# unban: "advancedban:unban %player%"
# unmute: "advancedban:unmute %player%"

# ===== SECURITY CONFIGURATION =====
#
# IMPORTANT: The 'histstaff' command reveals sensitive information including:
# - Who executed which commands
# - When they were executed
# - Which players were targeted
# - The reasons for the actions
#
# Make sure to grant access to this command only to your most trusted admins!
# The user IDs in the 'history-allowed-users' section should belong to
# your most trusted staff members.
#
# To obtain a Discord user's ID:
# 1. Enable Developer Mode in Discord
# 2. Right-click the user and select "Copy ID"